### ISSUE TITLE
Problems compiling tutorial 02

### ISSUE THREAD

**Issue by gfixler** [madjestic/Haskell-OpenGL-Tutorial#8]
Tutorials 00 and 01 worked fine, but 02 spits out a number of errors. I'm using ghc version 7.6.3.

    $ ghc --make Main.hs 
    [1 of 2] Compiling LoadShaders      ( LoadShaders.hs, LoadShaders.o )

    LoadShaders.hs:52:30:
        Not in scope: type constructor or class `ShaderType'

    LoadShaders.hs:62:4: Not in scope: `createProgram'

    LoadShaders.hs:62:35:
        Not in scope: `deleteObjectName'
        Perhaps you meant `deleteObjectNames' (imported from Graphics.Rendering.OpenGL)

    LoadShaders.hs:73:4: Not in scope: `createShader'

    LoadShaders.hs:73:41:
        Not in scope: `deleteObjectName'
        Perhaps you meant `deleteObjectNames' (imported from Graphics.Rendering.OpenGL)

    LoadShaders.hs:75:7:
        Not in scope: `shaderSourceBS'
        Perhaps you meant `shaderSource' (imported from Graphics.Rendering.OpenGL)

    LoadShaders.hs:77:7:
        Not in scope: `attachShader'
        Perhaps you meant `attachedShaders' (imported from Graphics.Rendering.OpenGL)

**Comment by madjestic** [comment]
Oh, cool!  Feedback! :D 

Thanks, I'll fix it asap.

**Comment by madjestic** [comment]
It should be fixed in the latest version.  Also tutorial 03 has been fixed and updated ;)  Thanks!
