### ISSUE TITLE
Question: Animations for Yampa's github

### ISSUE THREAD

**Issue by ivanperez-keera** [madjestic/Haskell-OpenGL-Tutorial#9]
This project is linked to from Yampa. Do you have any animations/gif that could be included in the readme to show people what kinds of things they can create? Possibly with fractals (I think it's one of the things you did, right?)

It might also be cool to include in this readme, of course :)

**Comment by madjestic** [comment]
Ok, I will put some animations together.

**Comment by madjestic** [comment]
[Some progress](https://github.com/madjestic/Haskell-OpenGL-Tutorial/tree/master/MandelbrotYampa)

**Comment by ivanperez-keera** [comment]
Nice! These fractals are pretty cool :)

**Comment by madjestic** [comment]
[updated README](https://github.com/madjestic/Haskell-OpenGL-Tutorial/tree/master/MandelbrotYampa) with an with an [animated gif](https://raw.github.com/madjestic/Haskell-OpenGL-Tutorial/master/MandelbrotYampa/output.gif)

Is that good enough?

**Comment by ivanperez-keera** [comment]
Nice!

Could you make it go slower? (probably just `dt / 10`  or `dt / 100` in the sensing action argument to reactimate).

By the way, out of curiosity, have you ever built any examples in which the fractal evolves in depth over time? (That is, you go one level deeper over time, but not necessarily zoom in.)

**Comment by madjestic** [comment]
I updated the [gif animation](https://raw.github.com/madjestic/Haskell-OpenGL-Tutorial/master/MandelbrotYampa/output.gif)

The Mandelbrot shader is pretty basic - it's just there to demonstrate the principle.  I am certainly planning to move into the glsl direction and try out more interesting shader, but at the moment it is what it is, sorry :)

**Comment by ivanperez-keera** [comment]
This is great! Thanks :)

Keep me posted about new animations and I'll see if I can link to them from the Yampa repo.

By the way, sometimes we also use these for talks (always mentioning who the author is).
